FROM node:latest

# Create app directory
RUN mkdir -p /usr/src/fronted
WORKDIR /usr/src/fronted

# Install app dependencies
COPY package.json /usr/src/fronted
# For npm@5 or later, copy package-lock.json as well
# COPY package.json package-lock.json ./
RUN npm install
# Bundle app source
COPY . /usr/src/fronted

EXPOSE 8080

CMD [ "npm","run","server" ]