FROM node:latest

# Create app directory
RUN mkdir -p /usr/src/backend
WORKDIR /usr/src/backend

# Install app dependencies
COPY package.json /usr/src/backend
# For npm@5 or later, copy package-lock.json as well
# COPY package.json package-lock.json ./
RUN rm -rf node_modules/bcrypt
RUN npm install

# Bundle app source
COPY . /usr/src/backend

EXPOSE 8080

CMD [ "npm","run","prod" ]